import {
  boolean,
  date,
  index,
  integer,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core"

export const entries = pgTable(
  "entries",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    handle: text("handle").notNull().unique(),
    timeSeconds: integer("time_seconds").notNull(),
    bootScreenUrl: text("boot_screen_url").notNull(),
    /**
     * The storage key behind that url, for deleting a replaced screen.
     *
     * Nullable because the seeded rows are files on the local disk with no key
     * at all, and because a url is not enough on its own — UploadThing offers
     * no way to derive a key from one.
     */
    bootScreenKey: text("boot_screen_key"),
    /**
     * Stable "source:id" identity, e.g. "x:123456".
     *
     * Not nullable: ranking goes through X, so every row has an account behind
     * it. This is the real owner — a handle can be renamed, an id cannot.
     */
    identityKey: text("identity_key").notNull().unique(),
    /**
     * Required hardware. Reported install times span roughly 45s to 8 minutes
     * on the same software, so a time without a machine attached compares to
     * nothing. Ids come from the catalogue in `src/lib/cpus.ts` rather than
     * free text, so they can be aggregated.
     */
    cpuId: text("cpu_id").notNull(),
    ramGb: integer("ram_gb").notNull(),
    storage: text("storage").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    /**
     * When this entry was taken down, and null while it is on the board.
     *
     * Hidden rather than deleted: a takedown made on a bad report has to be
     * one command to undo, and the rank has to survive the round trip. A row
     * is only really removed when the law requires it.
     */
    hiddenAt: timestamp("hidden_at", { withTimezone: true }),
  },
  // handle and identityKey are indexed by their UNIQUE constraints already.
  (t) => [
    index("entries_time_idx").on(t.timeSeconds),
    index("entries_updated_at_idx").on(t.updatedAt.desc()),
    index("entries_hidden_at_idx").on(t.hiddenAt),
  ],
)

/**
 * Someone flagging a boot screen.
 *
 * No reason field: the only thing that can be reported is one image, and
 * whoever reviews it is going to look at the image anyway. A select box would
 * buy a category nobody acts on differently.
 */
export const reports = pgTable(
  "reports",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    entryId: uuid("entry_id")
      .notNull()
      .references(() => entries.id, { onDelete: "cascade" }),
    /**
     * The caller, hashed. Enough to tell two reports apart, not enough to
     * hold onto an address for something nobody will ever need it for.
     */
    reporterKey: text("reporter_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // One per person per entry, so the count is people rather than clicks —
    // otherwise a single reporter holding a key down looks like a consensus.
    uniqueIndex("reports_entry_reporter_idx").on(t.entryId, t.reporterKey),
    index("reports_created_at_idx").on(t.createdAt.desc()),
  ],
)

export const visitorDays = pgTable(
  "visitor_days",
  {
    day: date("day").notNull(),
    visitorId: text("visitor_id").notNull(),
  },
  (t) => [primaryKey({ columns: [t.day, t.visitorId] })],
)

export const dailyStats = pgTable("daily_stats", {
  day: date("day").primaryKey(),
  views: integer("views").notNull().default(0),
})

export const presence = pgTable("presence", {
  visitorId: text("visitor_id").primaryKey(),
  lastSeen: timestamp("last_seen", { withTimezone: true }).notNull().defaultNow(),
})

/**
 * Better Auth's own tables, generated by `@better-auth/cli generate` and
 * pasted here so `schema.ts` stays the single source of truth for migrations.
 * Regenerate and re-fold if the auth config grows a field.
 *
 * One deliberate divergence from the generated output: timestamps are
 * `withTimezone`, matching every other table in this file.
 */
export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  /**
   * X only releases an address under a scope this app never asks for, so in
   * practice this is a non-routable placeholder. See `src/lib/identity.ts`.
   */
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  /** The X handle, lowercased. Set from the profile, never from a client. */
  handle: text("handle").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
})

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    token: text("token").notNull().unique(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [index("session_user_id_idx").on(t.userId)],
)

/** One row per provider account. `accountId` is the numeric X user id. */
export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    /**
     * Who vouched for the account — for X, a synthetic issuer Better Auth
     * derives itself. Required by Better Auth, and the CLI that generated the
     * rest of this omitted it, which failed the callback after the person had
     * already approved on X.
     */
    issuer: text("issuer").notNull(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index("account_user_id_idx").on(t.userId),
    // One account per provider identity.
    uniqueIndex("account_issuer_account_id_idx").on(t.issuer, t.accountId),
  ],
)

/** Short-lived OAuth state and PKCE verifiers; Better Auth prunes them. */
export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [index("verification_identifier_idx").on(t.identifier)],
)
